"""Reproduction tests: re-run calc.py scripts and compare against committed results.json.

Fast subset (sub-second, mostly exact sympy arithmetic) runs by default.
Set FULL_REPRO=1 to re-run all calculations (~50 min) with the documented
run-order dependencies respected (sj-far-zone needs sj-threshold-scan,
modular-flow-bd-4d needs modular-flow-corner; see REVIZE-PRO-CLOVEKA.md §4.3).

Pass criterion: no verdict flips, no structural diffs, and a two-tier numeric
tolerance calibrated by the 2026-06-07 cross-HW run (linux/x86_64 OpenBLAS vs
the verified macOS/arm64 Accelerate host, where runs are bit-identical):
- CORE fields: max relative deviation < 10%;
- DIAGNOSTIC fields (small-sample _std/_sem/_err spreads, fit exponents of
  near-zero pile-up counts, retardedness noise ratios): < 500% — these
  amplify ulp-level eigh differences and carry no physics verdicts;
- machine-precision residuals are handled by the noise floor inside
  repro-runner.compare (both sides < 1e-10 => equal).
Timing fields (runtime_s, timing_s) are ignored.
"""
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[2]
CALC = REPO / "core-data" / "calculations"
TMP = Path("/tmp/qg-repro-test")
TIMING_FIELDS = ("runtime_s", "timing_s", "elapsed_s", "wall_clock")
# Plot-file path fields are run-location-dependent metadata (the committed path
# is repo-relative, a sandbox re-run writes a /tmp-relative path) — not physics.
PATH_FIELDS = ("/plot",)

# Sub-second calculations, safe to run on every test invocation.
FAST_CALCS = [
    "a4-anomaly-matching",
    "a4-graviton-index",
    "bmv-as-phase",
    "ds-classification",
    "lambda-induced",
    "lambda-prefactors",
]

# Remaining calculations in dependency-aware order (run only with FULL_REPRO=1).
SLOW_CALCS = [
    "ssee-diamond",
    "sj-rotating-btz",
    "sj-kerr-equatorial",
    "sj-eigenvector-superradiance",
    "sj-threshold-scan",       # must precede sj-far-zone
    "sj-far-zone",
    "sj-vn-type",
    "ssee-4d",
    "ssee-bd-4d",
    "ssee-slab-4d",
    "vn-type-slab-4d",
    "modular-flow-corner",     # must precede modular-flow-bd-4d
    "modular-flow-bd-4d",
    "sj-desitter-type",
    # rounds 10-12 (lib/toe-based calcs)
    "sj-desitter-4d",
    "modular-flow-codim2",
    "ds-entropy-cap",
    "ds-tracial-probe",
    # round 13 (H6g-4 Lambda shot-noise; lib/toe counting primitives, ~26 s)
    "lambda-shot-noise",
    # round 16 (H6g-2 conformally-coupled 4D dS area-law; massive BD inverse)
    "ds-conformal-4d",
    # round 17 (H6g-6 codim-2 molecule FLUCTUATION; pure counting, no eigh, ~9 min)
    "ds-molecule-fluctuation",
    # rounds 14-19 numerical-coverage backfill (lib/toe-based, deterministic seeds)
    "modular-kms-thermal",     # F-034, ~10 s
    "ncg-kms-unruh",           # F-036, ~54 s
    "index-charge-discrete",   # H-E probe, ~56 s
    "amol-anomaly-ee-coeff",   # F-039 (H-B), ~4 min
    "spectral-triple-modular", # F-033, ~5.5 min
]

# Fields that amplify ulp-level eigh differences across BLAS implementations
# without carrying any physics verdict: small-sample seed spreads, fit
# exponents of near-zero (truncated pile-up) counts, retardedness noise
# ratios. Calibrated on the 2026-06-07 cross-HW matrix run.
DIAGNOSTIC_PAT = re.compile(
    r"(_std(\[|$)|_sem(\[|$)|_err$|knee_std|pile_below_eps0_(number|trunc)"
    r"|pile_trunc|retard"
    # float32 invariant residuals (~1e-7 scale, above the 1e-10 noise floor)
    # and derived significance-distance ratios (raw exponent+SE stay core):
    r"|hermiticity|_sigma(\[|$)|pairing"
    # standard-error fields (_se suffix family) and the float32 sparse
    # cross-check section (eigsh fit outputs wobble cross-BLAS; the primary
    # physics lives in the dense density/patch scans):
    r"|_se(\[|$)|_se_regression|high_density_sparse_consistency"
    # documented-pathological probe output (VYPOCET-06 honest negative):
    # the imposed-rank section is ill-conditioned by construction; its values
    # flip sign between CPU microarchitectures (eigenvector sign ambiguity).
    r"|area_law_imposed_rank)"
)

# Fields written post-hoc / by companion scripts, not regenerated by calc.py
# (provenance documented in reports/2026-06-06-review.md §(f)).
KNOWN_EXTRA_FIELDS = (
    "_se_regression",
    "_ci68_bootstrap",
    "_err_note",
    "err_note",
    "area_law_conditioning_check",
    "VERDICT",
)


def _load_runner():
    spec = importlib.util.spec_from_file_location(
        "repro_runner", REPO / "workflows" / "review-prep" / "repro-runner.py"
    )
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


RUNNER = _load_runner()


def _prepare(name: str) -> Path:
    """Copy a calc dir into the sandbox, keeping previously prepared siblings."""
    src, dst = CALC / name, TMP / name
    shutil.rmtree(dst, ignore_errors=True)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("plots", "__pycache__"))
    return dst


def _run_and_compare(name: str, timeout: int | None = None):
    if timeout is None:
        # Slower hosts (e.g. 4-vCPU CI runners) need more headroom than the
        # local reference machine — ssee-4d alone runs ~26 min there.
        timeout = int(os.environ.get("REPRO_CALC_TIMEOUT", "1800"))
    dst = _prepare(name)
    orig = json.loads((CALC / name / "results.json").read_text())
    env = dict(
        os.environ, OMP_NUM_THREADS="4", MPLBACKEND="Agg", PYTHONHASHSEED="0"
    )
    # calc.py scripts of rounds 10-12 import lib/toe; their __file__-relative
    # bootstrap resolves wrongly inside the /tmp sandbox copy, so provide the
    # repo lib via PYTHONPATH (harmless for the older self-contained calcs).
    env["PYTHONPATH"] = str(REPO / "lib") + (
        os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else ""
    )
    proc = subprocess.run(
        [sys.executable, "calc.py"],
        cwd=dst,
        env=env,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    assert proc.returncode == 0, f"{name}: calc.py failed\n{proc.stderr[-2000:]}"
    new = json.loads((dst / "results.json").read_text())

    diffs = [
        d
        for d in RUNNER.compare(orig, new)
        if not any(t in d[0] for t in TIMING_FIELDS)
        and not any(p in d[0] for p in PATH_FIELDS)
        and not (
            d[1] == "missing-in-new" and any(k in d[0] for k in KNOWN_EXTRA_FIELDS)
        )
    ]
    flips = [d for d in diffs if d[1] == "verdict-flip"]
    structural = [
        d for d in diffs if d[1] in ("missing-in-new", "new-key", "len-change", "value-change")
    ]
    nums = [d for d in diffs if d[1] == "num"]
    core = [d for d in nums if not DIAGNOSTIC_PAT.search(d[0])]
    diag = [d for d in nums if DIAGNOSTIC_PAT.search(d[0])]
    max_core = max((d[2] for d in core), default=0.0)
    max_diag = max((d[2] for d in diag), default=0.0)

    assert not flips, f"{name}: verdict flips {flips}"
    assert not structural, f"{name}: structural diffs {structural[:5]}"
    worst_core = sorted(core, key=lambda d: -d[2])[:5]
    assert max_core < 0.10, (
        f"{name}: max CORE relative deviation {max_core:.3e} >= 10%; "
        f"worst: {[(p, round(r, 4)) for p, _, r in worst_core]}"
    )
    worst_diag = sorted(diag, key=lambda d: -d[2])[:5]
    assert max_diag < 5.0, (
        f"{name}: max DIAGNOSTIC relative deviation {max_diag:.3e} >= 500%; "
        f"worst: {[(p, round(r, 4)) for p, _, r in worst_diag]}"
    )


@pytest.mark.parametrize("name", FAST_CALCS)
def test_fast_reproduction(name):
    _run_and_compare(name, timeout=120)


@pytest.mark.skipif(
    not os.environ.get("FULL_REPRO"),
    reason="set FULL_REPRO=1 to re-run all calculations (~50 min)",
)
@pytest.mark.parametrize("name", SLOW_CALCS)
def test_full_reproduction(name):
    # Dependency dirs are prepared by their own (earlier) parametrized run;
    # prepare them defensively in case of single-test invocation.
    deps = {
        "sj-far-zone": "sj-threshold-scan",
        "modular-flow-bd-4d": "modular-flow-corner",
        "modular-flow-codim2": "modular-flow-bd-4d",   # F-024 tip baseline
        "ds-entropy-cap": "ssee-diamond",              # F-006 epsilon (anti-circularity)
        "ds-conformal-4d": "ssee-diamond",             # F-006 epsilon (anti-circularity)
        "ds-molecule-fluctuation": "ssee-diamond",     # F-006 epsilon (anti-circularity)
        "amol-anomaly-ee-coeff": "ds-entropy-cap",     # F-029 c_EE channel (H-B)
    }
    if name in deps and not (TMP / deps[name] / "results.json").exists():
        _prepare(deps[name])  # committed results.json suffices as input
    _run_and_compare(name)
